"""initial migration

Revision ID: d1a650eefbda
Revises:
Create Date: 2025-07-22 15:04:38.858717

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d1a650eefbda"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "songs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("artist", sa.String(length=255), nullable=True),
        sa.Column("album", sa.String(length=255), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("fingerprinted", sa.Boolean(), nullable=True),
        sa.Column("file_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_songs_file_hash"), "songs", ["file_hash"], unique=True)
    op.create_table(
        "fingerprints",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("hash", sa.String(length=40), nullable=False),
        sa.Column("song_id", sa.UUID(), nullable=False),
        sa.Column("offset", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["songs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_hash_song", "fingerprints", ["hash", "song_id"], unique=False)
    op.create_index(
        op.f("ix_fingerprints_hash"), "fingerprints", ["hash"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fingerprints_hash"), table_name="fingerprints")
    op.drop_index("idx_hash_song", table_name="fingerprints")
    op.drop_table("fingerprints")
    op.drop_index(op.f("ix_songs_file_hash"), table_name="songs")
    op.drop_table("songs")
    # ### end Alembic commands ###
